extends Node

enum FoodType {
	NONE, APPLE, ORANGE, BREAD
}

enum StationType {
	NONE, FRIDGE, COUNTERTOP, STOVE, BLENDER, CHOPPING_BOARD, OVEN, DEEP_FRYER, SINK,
	MIXING_BOWL, TRASH_CAN
}

enum ToolType {
	NONE, TAMPER, KNIFE, SHEET_PAN, COOKING_POT, FRYING_BASKET, WOODEN_SPOON, SPONGE
}
